name: chocolatine

on:
  push:
    branches:
      - '**'
      - '!ga-ignore-*'
  pull_request:
    branches: 
      - '**'
      - '!ga-ignore-*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          find . -name "*.a" -o -name "*.exe" -o -name "*.o" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -name "*~" -o -name "#*#"
          echo test, and deploy your project.